name: projekt
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  email_validator: '^2.1.16'
  cupertino_icons: ^1.0.1
  provider: ^6.0.5
  graphql_flutter: ^5.1.2
  flutter_secure_storage: ^8.0.0
  device_info_plus: ^9.0.2
  google_nav_bar: ^5.0.6
  easy_debounce: ^2.0.3
  infinite_scroll_pagination: ^3.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png